server:
  port: 5002

node:
  storage: storage_node_5002
  id: http://localhost:5002
  peers:
    - http://localhost:5000
    - http://localhost:5001

logging:
  pattern:
    console: "%d{HH:mm:ss} %clr([%level]) %clr(%msg){faint}%n"


spring:
  output:
    ansi:
      enabled: ALWAYS